name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4     
    - name: Setup environment
      run: git config --global safe.directory '*'    
    - name: Build
      run: |
        make
        mkdir -p ~/artifacts
        cp pwalkerHax.3dsx ~/artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: ~/artifacts

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "pwalkerHax ${{ github.ref }}"
          files: artifacts/*
